### ISSUE TITLE
"'non-default argument follows default argument" error in sin_ifu_clean.py

### ISSUE THREAD

**Issue by edrick-afk** [reginasar/TNG_MaNGA_mocks#1]
when I was running the example script, it says the line 2218 of the sin_ifu_clean.py file (the first line of mk_intrinsic_assigned_maps funtion) produces a syntax error "non-default argument follows default argument". I already fixed it by putting the "template_SSP" argument in front of "fib_n=7", since I believe template_SSP is a default argument which should always proceed the non-default argument. 
I do not know how to create a pull request or ways to inform/suggest the error in the code, so I am putting it here for reference.

Best,
Edrick

**Comment by reginasar** [comment]
Solved! Thanks for contacting.
Known issues: running regrid on an RSS file produced with an IFU bundle smaller than 127 may lead to an error in the noise addition. This bug will be fixed in future updates.
